train:
  - TCGA-HU-A4GQ
  - TCGA-VQ-A924
  - TCGA-D7-A6EY
  - TCGA-BR-8487
  - TCGA-BR-8382
  - TCGA-BR-8591
  - TCGA-D7-A4YV
  - TCGA-HU-A4GN
  - TCGA-BR-8369
  - TCGA-BR-A4IY
  - TCGA-BR-7197
  - TCGA-BR-8286
  - TCGA-CD-A4MH
  - TCGA-EQ-8122
  - TCGA-EQ-A4SO
  - TCGA-HU-A4GC
val:
  - TCGA-HU-A4GT
  - TCGA-HU-A4H8
  - TCGA-MX-A5UJ
  - TCGA-RD-A8N6
  - TCGA-VQ-A94O
 
test:
  - TCGA-VQ-AA6D
  - TCGA-VQ-A94R 
